myapp/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :users

end

myapp/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token

  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,
            presence: true,
            length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # 与えられた文字列のハッシュ値を返す
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # ランダムなトークンを返す
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  # 永続的セッションで使用するユーザをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザログインを破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
end

myapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

myapp/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
    else
      flash.now[:danger] = 'invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

myapp/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

myapp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = 'Welcome to the Sample App!'
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

myapp/app/helpers/application_helper.rb
module ApplicationHelper
  # ページごとの完全なタイトルを返す
  def full_title(page_title = '')
    base_title = 'Ruby on Rails Tutorial Sample App'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

myapp/app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたユーザでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  # ユーザを永続的セッションに記憶する
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  # 記憶トークンcookieに対応するユーザを返す
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @curret_user = user
      end
    end
  end

  # ユーザがログインしていればtrue, その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  # 永続的セッションを破棄する
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  # 現在のユーザをログアウトする
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

myapp/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

myapp/app/helpers/users_helper.rb
module UsersHelper
  # 引数で与えられたユーザーのGravatar画像を返す
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

myapp/app/views/layouts/_footer.html.haml
%footer.footer
  %small
    The
    %a(href='http://www.railstutorial.org/')
      Ruby on Rails Tutorial
    by
    %a(href='http://www.michaelhartl.com/')
      Michael Hartl

  %nav
    %ul
      %li= link_to 'About', about_path
      %li= link_to 'Contact', contact_path
      %li
        %a(href='http://news.railstutorial.org')
          News

myapp/app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container
    = link_to 'sample app', root_path, id: 'logo'
    %nav
      %ul.nav.navbar-nav.navbar-right
        %li= link_to 'Home', root_path
        %li= link_to 'Help', help_path
        - if logged_in?
          %li= link_to 'Users', '#'
          %li.dropdown
            %a.dropdown-toggle{href:'#', 'data-toggle':'dropdown'}
              Account
              %b.caret
            %ul.dropdown-menu
              %li= link_to 'Profile', current_user
              %li= link_to 'Settings', '#'
              %li.divider
              %li= link_to 'Log out', logout_path, method: 'delete'

        - else
          %li= link_to 'Log in', login_path

myapp/app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = full_title(yield(:title))
    = stylesheet_link_tag('application', media: 'all', 'data-turbolinks-track': true)
    = javascript_include_tag('application', 'data-turbolinks-track': true)
    = csrf_meta_tags
  %body
    = render 'layouts/header'

    .container
      - flash.each do | message_type, message |
        .alert{:class => "alert-#{message_type}"}
          = message
      = yield

      = render 'layouts/footer'
      = debug(params) if Rails.env.development?

myapp/app/views/shared/_error_messages.html.haml
- if @user.errors.any?
  #error-explanation
    .alert.alert-danger
      The form contains
      = pluralize(@user.errors.count, 'error')
      \.

    %ul
      - @user.errors.full_messages.each do |msg|
        %li= msg

myapp/app/views/static_pages/about.html.haml
- provide(:title, "About")
%h1 About
%p
  The
  %a{:href => "http://www.railstutorial.org/"}
    %em
      Ruby on Rails Tutorial
  is a
  %a{:href => "http://www.railstutorial.jp/"}
    book
  and
  %a{:href => "http://creencasts.railstutorial.org"}
  This is the sample application for the tutorial.

myapp/app/views/static_pages/contact.html.haml
- provide(:title, "Contact")
%h1 Contact
%p
  TBD

myapp/app/views/static_pages/help.html.haml
- provide(:title, "Help")
%h1 Help
%p><
  Get help on the Ruby on Rails Tutorial at the
  %a(href="//railstutorial.jp/help")<
    Rails Tutorial help section

  To get help on this sample app, see the
  %a(href="//railstutorial.jp/help")
    %em
      Ruby on Rails Tutorial
    book
  \.

myapp/app/views/static_pages/home.html.haml
.center.jumpbotron
  %h1
    Welcome to the Sample App
  %h2
    This is the home page for the
    %a{:href => "http://www.railstutorial.org/"} Ruby on Rails Tutorial
    sample application.

  = link_to 'Sign up now!',
    signup_path,
    class: 'btn btn-lg btn-primary'

= link_to image_tag('rails.png',
    alt: 'Rails logo'),
    'http://rubyonrails.org/'

myapp/app/views/users/new.html.haml
- provide(:title, 'Sign up')
%h1 Users#new

.row
  .col-md-6.col-md-offset-3
    = form_for(@user) do |f|
      = render 'shared/error_messages'

      = f.label :name
      = f.text_field :name, class: 'form-control'

      = f.label :email
      = f.text_field :email, class: 'form-control'

      = f.label :password
      = f.text_field :password, class: 'form-control'

      = f.label :password_confirmation, 'Confirmation'
      = f.text_field :password_confirmation, class: 'form-control'

      = f.submit 'Create my account', class: 'btn btn-primary'

myapp/app/views/users/show.html.haml
- provide(:title, @user.name)
.row
  %aside.col-md-4
    %section.user-info
      %h1
        = gravatar_for @user
        = @user.name